ALTER TABLE `machine`.`report_data`
ADD COLUMN `MAX_SOLAR_V` DOUBLE DEFAULT 0 AFTER `UTILIT_P`,
ADD COLUMN `MAX_LOAD_V` DOUBLE DEFAULT 0 AFTER `MAX_SOLAR_V`,
ADD COLUMN `MAX_UTILIT_V` DOUBLE DEFAULT 0 AFTER `MAX_LOAD_V`,
ADD COLUMN `MAX_BATTERY_V` DOUBLE DEFAULT 0 AFTER `MAX_UTILIT_V`,
ADD COLUMN `MAX_SOLAR_C` DOUBLE DEFAULT 0 AFTER `MAX_BATTERY_V`,
ADD COLUMN `MAX_LOAD_C` DOUBLE DEFAULT 0 AFTER `MAX_SOLAR_C`,
ADD COLUMN `MAX_UTILIT_C` DOUBLE DEFAULT 0 AFTER `MAX_LOAD_C`,
ADD COLUMN `MAX_SOLAR_P` DOUBLE DEFAULT 0 AFTER `MAX_UTILIT_C`,
ADD COLUMN `MAX_LOAD_P` DOUBLE DEFAULT 0 AFTER `MAX_SOLAR_P`,
ADD COLUMN `MAX_UTILIT_P` DOUBLE DEFAULT 0 AFTER `MAX_LOAD_P`;