package util;

public interface Constants {
	public static final String IMEI_NO = "IMEI_NO";
	public static final String TIMESTAMP = "Timestamp";
	public static final String DATA1 = "data1";
	public static final String DATA2 = "data2";
	public static final String DATA3 = "data3";
	public static final String DATA4 = "data4";
	public static final String DATA5 = "data5";
	public static final String DATA6 = "data6";
	public static final String DATA7 = "data7";
	public static final String DATA8 = "data8";
	public static final String DATA9 = "data9";
	public static final String DATA10 = "data10";
	public static final String DATA11 = "data11";
	public static final String DATA12 = "data12";
	public static final String DATA13 = "data13";
	public static final String DATA14 = "data14";
	public static final String DATA15 = "data15";
	public static final String DATA16 = "data16";
	public static final String DATA17 = "data17";
	public static final String DATA18 = "data18";
	public static final String DATA19 = "data19";
	public static final String DATA20 = "data20";
	public static final String DATA21 = "data21";
	public static final String DATA22 = "data22";
	public static final String DATA23 = "data23";
	public static final String DATA24 = "data24";
	public static final String DATA25 = "data25";
	public static final String DATA26 = "data26";
	public static final String DATA27 = "data27";
	public static final String DATA28 = "data28";
	public static final String DATA29 = "data29";
	public static final String DATA30 = "data30";
	public static final String DATA31 = "data31";
	public static final String DATA32 = "data32";
	public static final String DATA33 = "data33";
	public static final String DATA34 = "data34";
	public static final String DATA35 = "data35";
	public static final String DATA36 = "data36";
	public static final String DATA37 = "data37";
	public static final String DATA38 = "data38";
	public static final String DATA39 = "data39";
	public static final String DATA40 = "data40";
}
